### ISSUE TITLE
SourceMap's sources list are incomplete.

### ISSUE THREAD

**Issue by emosheeep** [guoyunhe/swc-minify-webpack-plugin#11]
https://github.com/guoyunhe/swc-minify-webpack-plugin/blob/7c400dd24fb3653f6da5bfe4d70c3edce5b820bc/src/index.ts#L89

Maybe this line should be `map.sources` so that to inherit source list from `map` 🤔:

```ts
/** update sources */
if (map && output.map) {
  newMap.sources = map.sources
}
```

**Comment by guoyunhe** [comment]
Can you provide a reproduce repo? like https://github.com/guoyunhe/swc-minify-webpack-plugin/tree/main/example

**Comment by emosheeep** [comment]
Sorry I misunderstood, the sourcemap would be corrected by webpack-sources when you set `newMap.sources = [asset.name];`
