### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by JarrodMFlesch** [guoyunhe/swc-minify-webpack-plugin#5]
Is there a reason this package has a GPL3 license? Would you consider changing it to MIT license? 

With it being GPL3, anyone who uses this package will need to make their code publicly available (open source), and their license will also need to be GPL3.

Someone in our community brought this to our attention. We will have to remove this package from our dependencies if you want to keep it as GPL3. That is totally fine! I just figured I would reach out and see where you stood on this topic first 🙂

**Comment by guoyunhe** [comment]
New version 2.1.0 is released under Apache 2.0 license, the same license as SWC.

**Comment by JarrodMFlesch** [comment]
@guoyunhe Thanks for this and the quick reply!
