### ISSUE TITLE
Update README to Mention `format` Option

### ISSUE THREAD

**Issue by joealden** [guoyunhe/swc-minify-webpack-plugin#6]
Looking at the source of this plugin, this option is indeed supported (as you are just spreading the options passed to the plugin to swc), so maybe it's be worth updating the docs to reflect this (or just saying that all options from swcs minify are allowed)?

**Comment by guoyunhe** [comment]
@joealden Thanks for the tip! When I wrote this plugin, swc hasn't supported `format` option yet. I guess it is some kind of new feature.

**Comment by guoyunhe** [comment]
Updated README. Please checkout!

**Comment by joealden** [comment]
Looks great, thanks!
