### ISSUE TITLE
Uncorrect source maps after minification

### ISSUE THREAD

**Issue by Themezv** [guoyunhe/swc-minify-webpack-plugin#9]
## Source maps after minification should remaps source maps before. 

For example. 
1. We have two original files like index.ts and component.tsx
2. We have some webpack ts loader, for example swc-loader to transpile ts files.
3. After transpiling we minificate a final bundle. 

Actual source maps, produced by minificator, contains information only about already bundled code. 
Expected behavior: source maps after minification should contains information about index.ts and component.tsx

There are several packages that can remap source maps. For example https://github.com/mozilla/source-map or https://github.com/7rulnik/source-map-js or https://github.com/ampproject/remapping

**Comment by guoyunhe** [comment]
Should be fixed in 2.1.2. Let me know if it works or not.
